#!/bin/sh

STASH_PATH="/Users/electricSoda/toolsCP/stash.txt"

if [ -z "$1" ]
    then
        FILE=`grep prev $STASH_PATH| cut -d'=' -f2`
    else
        FILE="$1"
fi

echo "FILE $FILE"

sed -i '' -e "s/prev=.*/prev=$FILE/" $STASH_PATH

g++ $FILE -o ./result.exe -Wall -Wextra -O2 -std=c++11
echo "... DONE ..."
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -
./result.exe


